### ISSUE TITLE
OWL support within Amazon Neptune

### ISSUE THREAD

**Issue by supreme-core** [aws-samples/amazon-neptune-ontology-example-blog#25]
Hello,

I recently read your blog about Amazon Neptune's use of SPARQL and OWL- https://aws.amazon.com/blogs/database/model-driven-graphs-using-owl-in-amazon-neptune/ .

I've been testing OWL support across different RDF graph databases. Amazon Neptune stands out as it functions as both a property graph database and an RDF graph database, which is uncommon in the graph database industry. I'm interested in learning about your experiences with OWL support in Amazon Neptune, as OWL support was a crucial factor in my decision-making process.

This is not really an issue but more of a comment on your blog. Definitely looking forward to hearing what your thoughts on it.

**Comment by mhavey** [comment]
Hi Eric. True, Neptune supports both property graph and RDF. My blog post was focused on the RDF side of the house. Neptune "supports" OWL in the sense that OWL is itself expressed as RDF and can be ingested to the database along with the individuals themselves. I can them query them together in SPARQL. My blog post discussed why it is useful to have the ontology alongside the data for model-driven purposes like validation. What are your decision criteria about OWL support? Feel free to reach out directly to discuss further.
